project_admin/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count


class Project(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    active = models.BooleanField()
    approved = models.BooleanField()
    authorized_members = models.IntegerField()
    badge_image = models.URLField(max_length=200, blank=True, null=True)
    contact_email = models.EmailField(max_length=200)
    id = models.AutoField(primary_key=True)
    id_label = models.CharField(max_length=50)
    info_url = models.URLField(max_length=200, blank=True)
    is_academic_or_nonprofit = models.BooleanField()
    is_study = models.BooleanField()
    leader = models.CharField(max_length=50)
    long_description = models.TextField()
    name = models.CharField(max_length=50)
    organization = models.CharField(max_length=200, blank=True)
    registered_datatypes = models.TextField(default='')
    requested_sources = models.TextField(default='')
    request_sources_access = models.TextField()
    request_username_access = models.BooleanField()
    returned_data_description = models.CharField(max_length=200, blank=True)
    short_description = models.TextField()
    slug = models.SlugField(max_length=50)
    type = models.CharField(max_length=50)
    token = models.CharField(max_length=65)
    refreshed_at = models.DateTimeField(auto_now=True)


class ProjectGroup(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(default='')
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class ProjectMemberManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().annotate(
            file_count=Count('file')
        )


class ProjectMember(models.Model):
    id = models.IntegerField(primary_key=True)
    date_joined = models.DateTimeField()
    sources_shared = models.CharField(max_length=1000, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    groups = models.ManyToManyField(ProjectGroup)
    objects = ProjectMemberManager()
    username = models.CharField(max_length=200, null=True)


class File(models.Model):
    oh_file_id = models.IntegerField()
    basename = models.CharField(max_length=200)
    created = models.DateTimeField()
    download_url = models.URLField(max_length=512)
    source = models.CharField(max_length=50)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    member = models.ForeignKey(ProjectMember, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('oh_file_id', 'project')


class Note(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    member = models.ForeignKey(ProjectMember, on_delete=models.CASCADE)


class S3Upload(models.Model):
    key = models.CharField(max_length=260)
    created_at = models.DateTimeField(auto_now_add=True)

project_admin/templates/project_admin/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Uncomment the following if a favicon is added. -->
    <link rel="icon" type="image/png" href="{% static 'project_admin/favicon.ico' %}">

    <title>Open Humans Project Management</title>

    <!-- Bootstrap via CDN. -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Local CSS overrides -->
    <link href="{% static 'project_admin/main.css' %}" rel="stylesheet">

    <!--FontAwesome-->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'home' %}">
        Open Humans Project Management
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
            <li class="nav-item {% if page == 'home' %}active{% endif %}">
              <a class="nav-link" href="{% url 'home' %}">Project Details</a>
            </li>
            <li class="nav-item {% if page == 'members' %}active{% endif %}">
              <a class="nav-link" href="{% url 'members' %}">Member Details</a>
            </li>
            <li class="nav-item {% if page == 'groups' %}active{% endif %}">
              <a class="nav-link" href="{% url 'groups' %}">Group Details</a>
            </li>
            <li>
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item {% if page == 'login' %}active{% endif %}">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container my-5">

      {% if messages %}
        <div class="row">
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show w-100">
            <span>{{ message }}</span>
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endfor %}
        </div>
      {% endif %}

      {% block main_container %}
      <h1>Default content</h1>
      <p>
        This is default template content. Pages using this template are
        expected to replace this. (If you can see this, it's a bug.)
      </p>
      {% endblock main_container %}

    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- jQuery and Popper.js (necessary for Bootstrap's JS plugins) -->
    <script
    			  src="https://code.jquery.com/jquery-3.3.1.min.js"
    			  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    			  crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
-    <!-- Latest compiled and minified JavaScript via MaxCDN -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- Local JavaScript -->
    <script src="{% static 'project_admin/main.js' %}"></script>
  </body>
</html>

project_admin/templates/project_admin/files_modal.html
<div id="filesModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Files for member <span id='files_member_title'></span></h5>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <div id='filesModalBody'></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

project_admin/templates/project_admin/files_modal_body.html
{% if member.file_set.all|length > 0 %}
<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Source</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
  {% for file in member.file_set.all %}
    <tr>
      <td>{{ file.basename }}</td>
      <td>{{ file.source }}</td>
      <td>
        <a class="btn btn-sm bg-white border border-success text-success" href="{{ file.download_url }}">
          Download
        </a>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% else %}
  <div class="row">
    <div class="w-100 text-center mt-4 mb-3">
      <p>This user has not shared any files yet</p>
    </div>
  </div>
{% endif %}

project_admin/templates/project_admin/group_modal_add.html
<div id="addGroupModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
      <div class="modal-content">
      <div class="modal-header">
        <h5>Add Groups for <span id='groups_member_title'></span> </h5>
        <button align="right" type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <div id="addGroupModalBody"></div>
      </div>
      </div>
    </div>
  </div>

project_admin/templates/project_admin/group_modal_add_body.html
<form action="{% url 'add_to_groups' %}" method="post">
  {% csrf_token %}
  <input type="hidden" name="member_pk" value={{member.id}}>
  <div class="form-group">
    <select class="custom-select" name="selected_groups" id="selected_groups" multiple>
      {% for group in groups %}
        {% if group not in member.groups.all %}
            <option value= {{group.id}} title= "{{group.description}}">
              {{group.name}}({{group.id}})
            </option>
        {% endif %}
      {% endfor %}
    </select>
    <small class="form-text text-muted">Hold Ctrl/Cmd to select multiple groups</small>
  </div>
  <div class="modal-footer">
      <button type="submit" class="btn btn-outline-success float-right btn-sm">Submit</button>
  </div>
</form>

project_admin/templates/project_admin/group_modal_body.html
<table class="table">
  <thead>
  <tr>
    <th width="20">Group ID</th>
    <th width="20%">Name</th>
    <th width="50%">Description</th>
    <th width="10%">Action</th>
  </tr>
  </thead>
  <tbody>
  {% for group in member.groups.all %}
    <tr>
      <td>{{ group.id }}</td>
      <td>{{ group.name }}</td>
      <td>{{ group.description|linebreaks }}</td>
      <td>
        <a class="btn btn-sm btn-outline-danger" href="{% url 'remove_member' group.id member.id %}">
          Remove from group
        </a>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>

project_admin/templates/project_admin/login.html
{% extends 'project_admin/base.html' %}

{% block main_container %}

  <a href="https://www.openhumans.org/direct-sharing/projects/manage/" target="blank">
    Go to token page (dev-purpose)
  </a>
  <br><br/>
  <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="text-center">
        <input type="submit" value="Log in" class="btn btn-success"/>
      </div>
  </form>

{% endblock main_container %}

project_admin/templates/project_admin/member_card.html
<div class="card">
    <div class="card text-center">
      <div class="card-header">
      <nav>
        <div class="nav nav-tabs" role="tablist" id="memberTab">
          <a class="nav-item nav-link active" id="notes-tab" data-toggle="tab" href="#notes_{{member}}" role="tab" aria-controls="Notes" aria-selected="true">Notes</a>
          <a class="nav-item nav-link" id="groups-tab" data-toggle="tab" href="#groups_{{member}}" role="tab" aria-controls="Groups" aria-selected="false">Groups</a>
          <a class="nav-item nav-link"id="datashared-tab"  data-toggle="tab" href="#datashared_{{member}}" role="tab" aria-controls="Data Shared" aria-selected="false">Data Shared</a>
        </div>
      </nav>
      </div>

      <div class="tab-content" id="memberTabContent">
        <!--Notes-->
        <div class="tab-pane fade show active" id="notes_{{member}}" role="tabpanel" aria-labelledby="notes-tab">
          <button type="button" class="btn btn-outline-info btn-sm my-2" data-toggle="modal" data-target="#addNote_{{member}}">Add New Note</button>
            {% if member.note_set.all|length > 0 %}
            <table class="table">
              <thead>
              <tr>
                <th style="width: 20%">Created on</th>
                <th style="width: 20%">Last Modified on</th>
                <th style="width: 20%">Title</th>
                <th style="width: 20%">Description</th>
                <th style="width: 20%">Action</th>
              </tr>
              </thead>
              <tbody>
              {% for note in member.note_set.all %}
                <tr>
                  <td>{{ note.created_at }}</td>
                  <td>{{ note.modified_at }}</td>
                  <form action="{% url 'update_note' note.id %}" method="post">
                    {% csrf_token %}
                    <td>
                      <h10 class="note_{{ note.id }}_info collapse show">{{ note.title }}</h10>
                      <input type="text" class="form-control-sm w-100 note_{{ note.id }}_info collapse" name="note_{{ note.id }}_title" value="{{ note.title }}" required>
                    </td>
                    <td class="wrap">
                      <h10 class="note_{{ note.id }}_info collapse show">{{ note.description }}</h10>
                      <input type="text" class="form-control-sm w-100 note_{{ note.id }}_info collapse" name="note_{{ note.id }}_description" value="{{ note.description }}" required>
                    </td>
                    <td>
                      <div class="btn-group">
                        <a data-target=".note_{{ note.id }}_info" data-toggle="collapse" href="#" class="btn btn-sm btn-outline-info">
                            Edit
                        </a>
                        <button type="submit" class="note_{{ note.id }}_info collapse btn btn-sm btn-outline-success">
                          Save
                        </button>
                        <a class=" btn btn-sm btn-outline-danger" href="{% url 'delete_note' note.id %}">
                            Delete
                        </a>
                      </div>
                    </td>
                  </form>
                </tr>
              {% endfor %}
              </tbody>
            </table>
            {% else %}
              <div class="row">
                <div class="w-100 text-center mt-4 mb-3">
                  <p>This user has no notes yet</p>
                </div>
              </div>
            {% endif %}
        </div>

        <!--Groups-->
        <div class="tab-pane fade" id="groups_{{member}}" role="tabpanel" aria-labelledby="groups-tab">
          <button type="button" class="btn btn-outline-info btn-sm my-2" data-toggle="modal" data-target="#addToGroup_{{member}}_info_{{groups}}">Add to New Group</button>
          {% if member.groups.all|length > 0 %}
            <table class="table">
              <thead>
              <tr>
                <th width="20">Group ID</th>
                <th width="20%">Name</th>
                <th width="50%">Description</th>
                <th width="10%">Action</th>
              </tr>
              </thead>
              <tbody>
              {% for group in member.groups.all %}
                <tr>
                  <td>{{ group.id }}</td>
                  <td>{{ group.name }}</td>
                  <td>{{ group.description|linebreaks }}</td>
                  <td>
                    <a class="btn btn-sm btn-outline-danger" href="{% url 'remove_member' group.id member.id %}">
                      Remove from group
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          {% else %}
            <div class="row">
              <div class="w-100 text-center mt-4 mb-3">
                <p>This user is not part of any groups yet</p>
              </div>
            </div>
          {% endif %}
        </div>

        <!--Data Shared-->
        <div class="tab-pane fade" id="datashared_{{member}}" role="tabpanel" aria-labelledby="datashared-tab">
          {% if member.file_set.all|length > 0 %}
          <table class="table">
            <thead>
            <tr>
              <th style="width: 60%">Name</th>
              <th style="width: 20%">Source</th>
              <th style="width: 20%">Action</th>
            </tr>
            </thead>
            <tbody>
            {% for file in member.file_set.all %}
              <tr>
                <td>{{ file.basename }}</td>
                <td>{{ file.source }}</td>
                <td>
                  <a class="btn btn-sm bg-white border border-success text-success" href="{{ file.download_url }}">
                    Download
                  </a>
                </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
          {% else %}
            <div class="row">
              <div class="w-100 text-center mt-4 mb-3">
                <p>This user has not shared any files yet</p>
              </div>
            </div>
          {% endif %}
        </div>
    </div>

  </div>

  <!--Modals here-->
    <!--Add new note-->
    <section>
      <div id="addNote_{{member}}" class="modal fade" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5>New Note</h5>
              <button align="right" type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
              <form action="{% url 'create_note' member.id %}" method="post">
                  {% csrf_token %}
                  <div class="form-group">
                      <label for="new_note_title">Title</label>
                      <input type="text"  class="form-control" name="new_note_title" required>
                  </div>
                  <div class="form-group">
                      <label for="new_note_description">Description</label>
                      <textarea name="new_note_description" class="form-control" rows="4" required></textarea>
                  </div>
                  <div class="modal-footer">
                  <button type="submit" class="btn btn-outline-success float-right btn-sm">Submit</button>
                  </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Add member to group -->
    <section>
      <div id="addToGroup_{{member}}_info_{{groups}}" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
              <h5>Groups</h5>
              <button align="right" type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
              <form action="{% url 'add_to_groups' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="member_pk" value={{member.id}}>
                <div class="form-group">
                  <select class="custom-select" name="selected_groups" id="selected_groups" multiple>
                    {% for group in groups %}
                      {% if group not in member.groups.all %}
                          <option value= {{group.id}} title= "{{group.description}}">
                            {{group.name}}({{group.id}})
                          </option>
                      {% endif %}
                    {% endfor %}
                  </select>
                  <small class="form-text text-muted">Hold Ctrl/Cmd to select multiple groups</small>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-outline-success float-right btn-sm">Submit</button>
                </div>
              </form>
            </div>
            </div>
          </div>
        </div>
    </section>

    <!--Edit note-->
    <section>
      <div id="updateNote_{{note}}" class="modal fade" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5>Edit Note</h5>
              <button align="right" type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
              <form  method="post">
                  {% csrf_token %}
                  <div class="form-group">
                      <label for="edit_title">Title</label>
                      <input type="text"  class="form-control" name="edit_title" value="{{note.id}}" required>
                  </div>
                  <div class="form-group">
                      <label for="edit_description">Description</label>
                      <textarea name="edit_description" value=description class="form-control" rows="4" required></textarea>
                  </div>
                  <div class="modal-footer">
                  <button type="submit" class="btn btn-outline-success float-right btn-sm">Submit</button>
                  </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

project_admin/templates/project_admin/members.html
{% extends 'project_admin/base.html' %}

{% block main_container %}
{% load widget_tweaks %}
  <!--Filter-->
  <form method="get">
      <div class="well">
        <div class="row">
          <div class="form-group col-sm-2 ">
            {{ filter.form.id.label_tag }}
            {% render_field filter.form.id class="form-control" %}
          </div>
          <div class="form-group col-sm-3">
            {{ filter.form.date_joined.label_tag }}
            {% render_field filter.form.date_joined class="form-control" %}
          </div>
          <div class="form-group col-sm-2">
            {{ filter.form.sources_shared.label_tag }}
            {% render_field filter.form.sources_shared class="form-control" %}
          </div>
          <div class="form-group col-sm-3">
            {{ filter.form.file_count.label_tag }}
          <div>
             {% render_field filter.form.file_count class="form-control" %}
           </div>
        </div>
          <div class="form-group col-sm-2">
              {{ filter.form.groups.label_tag }}
            <div>
               {% render_field filter.form.groups class="form-control" %}
             </div>
          </div>
        </div>
        <div class="mb-5">
          <button type="submit" class="btn btn-outline-primary float-right">
            Search
          </button>
        </div>
      </div>
    </form>

    <form action="{% url 'batch_processing' %}" method="post">
      {% csrf_token %}
      <input type="hidden" id="id" name="id" value="{{filter.data.id}}">
      <input type="hidden" id="date_joined" name="date_joined" value="{{filter.data.date_joined}}">
      <input type="hidden" id="sources_shared" name="sources_shared" value="{{filter.data.sources_shared}}">
      <input type="hidden" id="file_count" name="file_count" value="{{filter.data.file_count}}">
      <input type="hidden" id="groups" name="groups" value="{{filter.data.groups}}">
      <a class="my-2 btn btn-sm btn-outline-info" href="{% url 'download_metadata' %}">Download metadata of all users</a>
      <a class="my-2 btn btn-sm btn-outline-info" href="{% url 'download_zip_file' %}">Download data files of all users</a>
      <input type="submit" class='my-2 btn btn-sm btn-outline-info' value="Group filtered set" name="group" />
      <input type="submit" class='my-2 btn btn-sm btn-outline-info' value="Group filtered set & download all data for its members" name="download" />
</form>
    <!--Members-->
    <table class="table">
      <thead>
        <tr>
          {% if project.request_username_access %}
          <th>Username (Project Member ID)</th>
          {%else%}
          <th>Project Member ID</th>
          {%endif%}
          <th>Date joined</th>
          <th>Sources Authorized</th>
          <th>Number of Files Shared</th>
          <th>Groups Joined</th>
          <th>Notes</th>
        </tr>
      </thead>
      <tbody>
        {% for member in members %}
        <tr>
              {% if project.request_username_access %}
              <td>
                {{member.username}} ({{ member.id }})
              </td>
              {%else%}
              <td>{{ member.id }}</td>
              {%endif%}
              <td>{{ member.date_joined }}</td>
              <td>{{ member.sources_shared }}</td>
              <td>
                    {{member.file_count}}
                    <a href="#filesModal" data-member_id="{{member.id}}" data-toggle="modal"><span data-toggle="tooltip" data-container='body' data-placement="top" title='Click to see files' type="button" class="badge badge-info"><i class="fas fa-eye"></i></span></a>
              </td>
              <td>
                {% for group in member.groups.all %}
                  {% if not forloop.first %}, {% endif %}
                    {{group.name}}
                  {% empty %}
                    <em class="text-muted">No group</em>
                {% endfor %}
                <a href="#groupModal" data-member_id="{{member.id}}" data-toggle="modal"><span data-toggle="tooltip" data-container='body' data-placement="top" title='Click to see/edit groups' type="button" class="badge badge-info"><i class="fas fa-pencil-alt"></i></span></a>
              </td>
              <td>
                {{member.note_set.all.count}}
                <a href="#notesModal" data-member_id="{{member.id}}" data-toggle="modal"><span data-toggle="tooltip" data-container='body' data-placement="top" title='Click to see/edit notes' type="button" class="badge badge-info"><i class="fas fa-pencil-alt"></i></span></a>
              </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <nav aria-label="pagination">
      <ul class="pagination">
        {% if members.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1&id={{request.GET.id}}&date_joined={{request.GET.date_joined}}&sources_shared{{request.sources_shared.id}}=&file_count={{request.GET.file_count}}&groups={{request.GET.groups}}">&laquo; first</a></li>
            <li class="page-item"><a class="page-link" aria-label="Previous" href="?page={{ members.previous_page_number }}&id={{request.GET.id}}&date_joined={{request.GET.date_joined}}&sources_shared{{request.sources_shared.id}}=&file_count={{request.GET.file_count}}&groups={{request.GET.groups}}">previous</a></li>
        {% endif %}
            <li class="page-item active"><a class="page-link" href='#'>Page {{ members.number }} of {{ members.paginator.num_pages }}</a></li>
        {% if members.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ members.next_page_number }}&id={{request.GET.id}}&date_joined={{request.GET.date_joined}}&sources_shared{{request.sources_shared.id}}=&file_count={{request.GET.file_count}}&groups={{request.GET.groups}}">next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ members.paginator.num_pages }}&id={{request.GET.id}}&date_joined={{request.GET.date_joined}}&sources_shared{{request.sources_shared.id}}=&file_count={{request.GET.file_count}}&groups={{request.GET.groups}}">last &raquo;</a></li>
        {% endif %}
      </ul>
</nav>

 {% include 'project_admin/group_modal.html' %}
 {% include 'project_admin/notes_modal.html' %}
 {% include 'project_admin/files_modal.html' %}

{% endblock main_container %}

project_admin/templates/project_admin/notes_modal_add.html
<div id="addNoteModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5>New Note for <span id='new_notes_member_title'></span></h5>
        <button align="right" type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <div id="addNoteModalBody"></div>
      </div>
    </div>
  </div>
</div>

project_admin/templates/project_admin/notes_modal_body.html
{% if member.note_set.all|length > 0 %}
<table class="table">
  <thead>
  <tr>
    <th style="width: 20%">Created on</th>
    <th style="width: 20%">Last Modified on</th>
    <th style="width: 20%">Title</th>
    <th style="width: 20%">Description</th>
    <th style="width: 20%">Action</th>
  </tr>
  </thead>
  <tbody>
  {% for note in member.note_set.all %}
    <tr>
      <td>{{ note.created_at }}</td>
      <td>{{ note.modified_at }}</td>
        <td>
          <h10 class="note_{{ note.id }}_info collapse show">{{ note.title }}</h10>
        </td>
        <td class="wrap">
          <h10 class="note_{{ note.id }}_info collapse show">{{ note.description }}</h10>
        </td>
        <td>
          <div class="btn-group">
            <a class=" btn btn-sm btn-outline-danger" href="{% url 'delete_note' note.id %}">
                Delete
            </a>
          </div>
        </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% else %}
  <div class="row">
    <div class="w-100 text-center mt-4 mb-3">
      <p>This user has no notes yet</p>
    </div>
  </div>
{% endif %}